---

- name: Install dunst
  ansible.builtin.dnf:
    name:
      - dunst
    state: latest
  become: yes

- name: Copy hyprland conf
  ansible.builtin.template:
    src: "{{ item.file }}"
    dest: "~/.config/hypr/{{ item.file | replace('.j2', '') }}"
    mode: "{{ item.mode }}"
  loop:
    - { file: dunstrc.j2, mode: '0600' }
