---

- name: Check directory exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
  loop:
    - ~/.config/eww
    - ~/.config/hypr/eww/
    - ~/.config/hypr/eww/scripts

- name: Copy files
  ansible.builtin.copy:
    src: "eww/{{ item.file }}"
    dest: "~/.config/hypr/eww/{{ item.file }}"
    mode: "{{ item.mode }}"
  loop:
    - { file: scripts/, mode: '0700' }
    - { file: components/, mode: '0600' }

- name: Copy eww conf
  ansible.builtin.template:
    src: "eww/{{ item.file }}"
    dest: "~/.config/hypr/eww/{{ item.file }}"
    mode: "{{ item.mode }}"
  loop:
    - { file: eww.scss, mode: '0600' }
    - { file: eww.yuck, mode: '0600' }
    - { file: components/workspaces.yuck, mode: '0600' }
    - { file: scripts/start, mode: '0700' }
