---

# From https://raw.githubusercontent.com/Duckonaut/hyprload/main/install.sh

- name: Download the hyprload repo
  ansible.builtin.git:
    repo: 'https://github.com/duckonaut/hyprload.git'
    dest: '~/.local/share/hyprload/src'
    depth: 1
    update: yes
    single_branch: yes
    version: main
  register: hyprload_dl

- name: Build hyprload
  ansible.builtin.command: bash -c "HYPRLAND_HEADERS=/usr/include/hyprland make -C ~/.local/share/hyprload/src clean"

- name: Build hyprload
  ansible.builtin.command: bash -c "HYPRLAND_HEADERS=/usr/include/hyprland make -C ~/.local/share/hyprload/src install"

- name: Copy hyprload conf
  ansible.builtin.template:
    src: "{{ item.file }}"
    dest: "~/.config/hypr/{{ item.file | replace('.j2', '') }}"
    mode: "{{ item.mode }}"
  loop:
    - { file: hyprload.toml.j2, mode: '0600' }
