---

- name: Enable solopasha/hyprland
  community.general.copr:
      host: copr.fedorainfracloud.org
      state: enabled
      name: solopasha/hyprland
  become: yes

- name: Install hyprland support
  ansible.builtin.dnf:
    name:
      - hyprland-nvidia
      - hyprpicker # Colorpicker
      - wl-clipboard # For hyprpicker
      - xdg-desktop-portal-hyprland # Screensharing
      - pipewire # Screensharing
      - wireplumber # Screensharing
      - eww-wayland-git
      - playerctl # To control media
      - "@C Development Tools and Libraries" # For hyprload
      - pixman-devel # For hyprload
      - libglvnd-devel # For hyprload
      - cairo-devel # For hyprload
      - hyprland-devel # For hyprload
      - libdrm-devel # For hyprload
      - libinput-devel # For hyprload
      - libudev-devel # For hyprload
      - wayland-devel # For hyprload
      - libxkbcommon-devel # For hyprload
      - xcb-util-wm-devel # For hyprload
    state: latest
  become: yes

- name: Check directory exist
  ansible.builtin.file:
    path: ~/.config/hypr/
    state: directory
    mode: '0700'