---

- name: Install kitty
  ansible.builtin.dnf:
    name:
      - kitty
    state: latest
  become: yes

- name: Copy kitty conf
  ansible.builtin.template:
    src: "{{ item.file }}"
    dest: "~/.config/hypr/{{ item.file | replace('.j2', '') }}"
    mode: "{{ item.mode }}"
  loop:
    - { file: kitty.conf.j2, mode: '0600' }
