---

- ansible.builtin.import_tasks: hyprland_install.yml
  name: hyprland_install

- ansible.builtin.import_tasks: dunst.yml
  name: dunst

- ansible.builtin.import_tasks: kitty.yml
  name: kitty

- ansible.builtin.import_tasks: eww.yml
  name: eww

- ansible.builtin.import_tasks: swww.yml
  name: swww

- ansible.builtin.import_tasks: hyprload.yml
  name: hyprload

- ansible.builtin.import_tasks: hyprland_configure.yml
  name: hyprland_configure