---
- name: Install secure arch linux environment
  hosts: hosts
  connection: local
  become: true

  roles:
    - { role: base, tags: ['base'] }
    - { role: shell, tags: ['shell'] }
    - { role: keepass, tags: ['keepass'] }
    - { role: spotify, tags: ['spotify'] }
    - { role: games, tags: ['games'] }