---

- name: Pacman config setup
  ansible.builtin.copy:
      src: pacman.conf
      dest: /etc/

- name: Update pacman package cache
  pacman:
      update_cache: true
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Perform full system upgrade
  pacman:
      update_cache: true
      upgrade: true
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install base packages
  pacman:
      name: "{{ base_packages }}"
      state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install yay as aur helper
  aur:
      name: yay
      user: "{{ user.name }}"
      skip_pgp: true
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2